# Generated by Django 3.2 on 2023-11-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanDtxPrototypeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireexercise',
            old_name='input_text',
            new_name='result_13_ad_exer_type',
        ),
        migrations.RenameField(
            model_name='questionnaireexercise',
            old_name='result_13',
            new_name='result_13_exer_type',
        ),
        migrations.RenameField(
            model_name='questionnairenutrition',
            old_name='input_text_2',
            new_name='result_11_consume_num',
        ),
        migrations.RenameField(
            model_name='questionnairenutrition',
            old_name='input_text_1',
            new_name='result_11_snack_type',
        ),
        migrations.RemoveField(
            model_name='questionnairegad7',
            name='result_8',
        ),
        migrations.RemoveField(
            model_name='questionnairegad7',
            name='result_9',
        ),
        migrations.AddField(
            model_name='questionnaireexercise',
            name='result_13_boolean',
            field=models.BooleanField(blank=True, default=False, verbose_name='13번 문항 입력 여부'),
        ),
        migrations.AddField(
            model_name='questionnairenutrition',
            name='result_11_boolean',
            field=models.BooleanField(blank=True, default=False, verbose_name='11번 문항 입력 여부'),
        ),
    ]
