# Generated by Django 3.2 on 2024-01-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanDtxPrototypeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaireissuechecking',
            unique_together=set(),
        ),
    ]
