# Generated by Django 4.2.5 on 2023-09-21 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hanDtxPrototypeApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 21, 5, 44, 3, 929696, tzinfo=datetime.timezone.utc
                ),
                verbose_name="생성 날짜",
            ),
        ),
    ]
