# Generated by Django 3.2 on 2023-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanDtxPrototypeApp', '0002_auto_20231129_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(help_text='ExerciseType pk', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionnaireexercise',
            name='result_13_boolean',
        ),
        migrations.RemoveField(
            model_name='questionnaireexercise',
            name='result_13_exer_type',
        ),
        migrations.AddField(
            model_name='questionnaireexercise',
            name='result_13_exer_type',
            field=models.ManyToManyField(to='hanDtxPrototypeApp.ExerciseType'),
        ),
    ]
