# Generated by Django 3.2 on 2023-12-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanDtxPrototypeApp', '0005_questionnaireexercise_result_13_exer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireexercise',
            old_name='result_13_ad_exer_type',
            new_name='result_13_input_text',
        ),
        migrations.RemoveField(
            model_name='questionnairenutrition',
            name='result_11_boolean',
        ),
    ]
